
import Link from 'next/link';
import Image from "next/image";
import interview from "../../../public/interview.png"
import persona from "../../../public/persona.png"
import document from "../../../public/document.png"
export default function Cards() {

  return (
    <div className="w-full mt-5">
    <div className="grid md:grid-cols-3 gap-4 md:gap-2  text-white max-w-screen-xl mx-auto transform transition-transform duration-300 justify-items-center">
      
      
      <div className="max-356 card bg-base-100 md:w-62 lg:w-82 w-86  shadow-sm flex flex-col rounded-4xl hover:scale-105 ">
        <div className="relative w-full h-56 ">
          <Image
            src={document}
            alt="Shoes"
            fill
            className="rounded-4xl"
          />
        </div>
        <div className="card-body ">
          <h2 className="card-title">Generate MCQs from Documents</h2>
          <p>
            Upload any study material and get multiple-choice questions automatically generated by AI.
          </p>
          <div className="card-actions justify-end">

            <Link href="/mcq">
            <button className="btn text-[#D9E3F0]  bg-orange-400">START NOW</button>
            </Link>
            
          </div>
        </div>
      </div>


      <div className="card max-356 bg-base-100 md:w-62 lg:w-82  w-86   shadow-sm flex flex-col rounded-4xl hover:scale-105">
        <div className="relative w-full h-56 ">
          <Image
            src={interview}
            alt="Shoes"
            fill
            className="rounded-4xl"
          />
        </div>
        <div className="card-body ">
          <h2 className="card-title">Practice with AI Interviewer</h2>
          <p>
            Simulate real-time interviews tailored to your subject or job role and improve your confidence.
          </p>
          <div className="card-actions justify-end">
            <Link href="/interview">
            <button className="btn text-[#D9E3F0]  bg-orange-400">START NOW</button>
            </Link>
          </div>
        </div>
      </div>


      <div className="card max-356 bg-base-100 md:w-62 lg:w-82  w-86  shadow-sm flex flex-col rounded-4xl hover:scale-105">
        <div className="relative w-full h-56 ">
          <Image
            src={persona}
            alt="Shoes"
            fill
            className="rounded-4xl"
          />
        </div>
        <div className="card-body ">
          <h2 className="card-title"> Create Your Own AI Teacher and Chat</h2>
          <p>
            Build a custom learning persona based on your favorite teacher or expert to guide your studies.
          </p>
          <div className="card-actions justify-end">
            <Link href="/persona">
            <button className="btn text-[#D9E3F0]  bg-orange-400">START NOW</button>
            </Link>
          </div>
        </div>
      </div>

      
      
      </div>
    </div>
  );
}
